# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='audio_review',
            field=models.FileField(blank=True, null=True, upload_to=reviews.models.get_upload_file_name),
        ),
    ]
